services:
  web_sunucum:
    image: ghcr.io/mehmetbayram9000/devops:latest
    expose:
      - "5000"
    restart: always

  nginx_lb:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web_sunucum

  veritabani:
    image: redis:latest
    volumes:
      - redis_verisi:/data
    restart: always

# İŞTE BURASI HAYAT KURTARAN NOKTA:
volumes:
  redis_verisi:
    environment:
      - REDIS_URL=veritabani
