name: Otomatik Canlıya Alış

on:
  push:
    branches: [ main ] # Sadece ana koda bir şey ekleyince çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Sunucuya Gizli Tünel Aç ve Güncelle
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_SSH_KEY }}
            script: |
            cd /home/ubuntu/devops
            git pull origin main
            chmod +x deploy.sh
            ./deploy.sh
